import nodemailer from "nodemailer";

let _transporter: nodemailer.Transporter | null = null;

function getTransporter(): nodemailer.Transporter {
  if (!_transporter) {
    _transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || "smtp.gmail.com",
      port: parseInt(process.env.SMTP_PORT || "587"),
      secure: false,
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });
  }
  return _transporter;
}

export interface EscalationEmailPayload {
  userId: string;
  userName: string;
  userEmail: string;
  conversationSummary: string;
  issue: string;
}

export async function sendEscalationEmail(payload: EscalationEmailPayload): Promise<boolean> {
  const supportEmail = process.env.SUPPORT_EMAIL || "support@swarajdesk.in";

  try {
    const transporter = getTransporter();

    await transporter.sendMail({
      from: `"SwarajDesk Help AI" <${process.env.SMTP_USER || supportEmail}>`,
      to: supportEmail,
      subject: `[Help AI Escalation] User ${payload.userName} needs support`,
      html: `
        <h2>Help AI Escalation Report</h2>
        <p><strong>User:</strong> ${escapeHtml(payload.userName)} (${escapeHtml(payload.userEmail)})</p>
        <p><strong>User ID:</strong> ${escapeHtml(payload.userId)}</p>
        <p><strong>Issue Summary:</strong> ${escapeHtml(payload.issue)}</p>
        <hr>
        <h3>Conversation Summary</h3>
        <pre style="white-space: pre-wrap; font-family: sans-serif;">${escapeHtml(payload.conversationSummary)}</pre>
        <hr>
        <p><em>This email was auto-generated by SwarajDesk Help AI.</em></p>
      `,
    });

    return true;
  } catch (error) {
    console.error("[Email] Failed to send escalation email:", error);
    return false;
  }
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
