version: '3.8'

services:
  monitoring:
    image: ogadityahota/swaraj-ec2-depy-monitor:latest
    container_name: monitoring_service
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.key:/ec2-keys:ro
    environment:
      - EC2_SSH_KEY=/ec2-keys/ec2-iit-pair
